## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'mockexamples'

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_mockexamples' #to modify
description = 'Set of advanced Mock examples to test PyMoDAQ functionnalities'

author = 'Sebastien J. Weber'
author-email = 'sebastien.weber@cnrs.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.8']
